### ISSUE TITLE
Calling InstallPackage with a repro that doesn't exist (e.g. http://packagesource1) doesn't throw an exception

### ISSUE THREAD

**Issue by PeterJausovec** [NuGet/NuGet.VisualStudioExtension#10]
I was expecting an exception to be thrown from PackageInstaller.InstallPackage (from IVsPackageInstaller) when source = "http://packagesource" (or something that doesn't exist).

**Comment by emgarten** [comment]
Exceptions will now be surfaced to the IVsPackageInstaller caller in NuGet 3.0.0. This was a regression from the previous 2.8.3 behavior.

Fixed with: d3ef6171de6f76f606fd56969a1190c1be16b067
