### ISSUE TITLE
if the filter "Upgrade available" is choosen, then the default action should be "Upgrade"

### ISSUE THREAD

**Issue by DerAlbertCom** [NuGet/NuGet.VisualStudioExtension#11]
I've just installed AngularJS in seven projects ... instead of updated one.

And it happens before to me.

**Comment by deepakaravindr** [comment]
@DerAlbertCom , Filed https://github.com/NuGet/Home/issues/316 for this. We will soon be disabling issues from this repository and all issues need to be filed at https://github.com/NuGet/Home/issues
