### ISSUE TITLE
Calling InstallPackage with version being null or empty string throws an exception

### ISSUE THREAD

**Issue by PeterJausovec** [NuGet/NuGet.VisualStudioExtension#12]
I am using the InstallPackage from IVsPackageInstaller2 and I get this when passing empty/null string for version

Value cannot be null.
Parameter name: packageIdentity.Version 

Null/empty string used to work before, what do I need to pass in to have the latest NuGet package installed?

**Comment by emgarten** [comment]
I've updated IVsPackageInstaller2 to allow null versions, the highest version of the package found in the given sources will be used.
