### ISSUE TITLE
IsPackageInstalled returns false, even though package is installed in the project

### ISSUE THREAD

**Issue by PeterJausovec** [NuGet/NuGet.VisualStudioExtension#13]
Call to IsPackageInstalled on IVsPackageInstallerServices returns false, even though package is installed.

**Comment by deepakaravindr** [comment]
@PeterJausovec , Filed https://github.com/NuGet/Home/issues/314 for this. We will soon be disabling issues from this repository and all issues need to be filed at https://github.com/NuGet/Home/issues
