### ISSUE TITLE
Prerelease channel for Visual Studio 2013

### ISSUE THREAD

**Issue by vossad01** [NuGet/NuGet.VisualStudioExtension#14]
Any chance of prerelease builds for VS2013?  I did track down there are [3.0 releases on codeplex](http://nuget.codeplex.com/releases), but those appear to be VS14/VS2015 only.

Ideally I am looking for a build that is compatible with the KRE -> DNX rename.  As that seems to break package dependency resolution in NuGet 2.8.3, restricting VS2013 users to pre-DNX packages.  

Ref aspnet/Configuration#154

**Comment by csharpfritz** [comment]
We do have a fix in the works for older versions of Visual Studio to be able to support packages that reference the DNX target framework.  

Are there specific packages that you are having a problem with?

**Comment by vossad01** [comment]
The packages in [`aspnetvnext`](https://www.myget.org/gallery/aspnetvnext).

I discovered the issue trying to install `Microsoft.Framework.ConfigurationModel` beta4-10982 (issue details reported at aspnet/Configuration#154).  I we are also using EntityFramework 7 from there which pulls in a large number of dependencies and has the same issue.

For now I have just frozen on either the version we are currently using or the last pre-DNX release listed in aspnet/Home#377.  Though, this only works until we need a fix or feature from later versions.

It did seem that in a pinch I can manually edit the `.nupkg`s to get a working copy, but that is too intensive to do for regular updates.

**Comment by yishaigalatzer** [comment]
There you go, please reopen the issue if this doesn't solve your problem
https://nuget.codeplex.com/releases/view/612846
