### ISSUE TITLE
InstallPackage doesn't install anything, no exceptions either

### ISSUE THREAD

**Issue by PeterJausovec** [NuGet/NuGet.VisualStudioExtension#15]
Using NuGet Package MAnager version 3.0.60225.100. NuGet package is not installed when calling IVsPackageInstaller.InstallPackage. Trying to install package from the NuGet manager works fine. Our call to the InstallPackage method hasn't changed.

**Comment by emgarten** [comment]
This has been fixed in the latest build and will be in VS.
