### ISSUE TITLE
IVsPackageInstallerServices.GetInstalledPackages returns zero in 2015

### ISSUE THREAD

**Issue by kzu** [NuGet/NuGet.VisualStudioExtension#18]
Here's a repro xunit test for VS2015: http://cloud.cazzulino.com/NuGetTests.7z

May be related to #13. 

This is a blocker for a feature in Xamarin that retargets nuget packages when migrating a project from "Classic" to the new "Unified" API (from MonoTouch target framework to Xamarin.iOS).

**Comment by deepakaravindr** [comment]
@kzu, Filed https://github.com/NuGet/Home/issues/313 for this. We will soon be disabling issues from this repository and all issues need to be filed at https://github.com/NuGet/Home/issues

**Comment by kzu** [comment]
Thanks!
