### ISSUE TITLE
InstallPackage returns true, even though the source doesn't exist

### ISSUE THREAD

**Issue by PeterJausovec** [NuGet/NuGet.VisualStudioExtension#2]
Using latest build from master: 
Call InstallPackage and pass in e.g. "http://packagesource1" - the method returns true, even though the source doesn't exist.

**Comment by emgarten** [comment]
InstallPackage does not return a value, are you seeing incorrect results after the install from a different API call?

**Comment by PeterJausovec** [comment]
Closing this. Will open a separate issue where the exception is being thrown when calling InstallPackage.
