### ISSUE TITLE
Call to GetSources to get official sources returns an empty list

### ISSUE THREAD

**Issue by PeterJausovec** [NuGet/NuGet.VisualStudioExtension#3]
Using latest build from master.

Calling GetSources(false /* include unofficial */, false /* include disabled*/) to return the list of official sources, returns an empty list. I was expecting a list of official sources.

**Comment by emgarten** [comment]
PackageSource.IsOfficial is showing up as false for all sources coming from NuGet.Configuration

**Comment by emgarten** [comment]
Fixed with a2a4652b0db1494680017b9dc43113e5c6a01905
