### ISSUE TITLE
Feature suggestion: Multiple updates.

### ISSUE THREAD

**Issue by Bartmax** [NuGet/NuGet.VisualStudioExtension#9]
It would be great if one can select multiple project and update them all in once action.

Let's say I have 
Microsoft.Owin.Security.Facebook
Microsoft.Owin.Security.Google
Microsoft.Owin.Security.Twitter

the update all was removed (i can understand why) but it would be much better if I can just pick multiple packages and update all at once.

Thanks

**Comment by emgarten** [comment]
update-package (with no params) from the powershell console still allows you to update all packages, there are a few other options there that might help you out for bulk operations.

**Comment by Bartmax** [comment]
thing is, i don't want to update all, i want to update some.

**Comment by emgarten** [comment]
The team is taking a look at bringing back update all in the UI, we'll take a look at how updating just a set of packages together could work also.

**Comment by deepakaravindr** [comment]
@Bartmax, Filed https://github.com/NuGet/Home/issues/315 for this. We will soon be disabling issues from this repository and all issues need to be filed at https://github.com/NuGet/Home/issues
